import React, { createContext, useContext, useState } from "react";

export type Language = "en" | "es" | "hi" | "gu";

const translations = {
  en: {
    welcome: "Welcome Back",
    createAccount: "Create Account",
    fullName: "Full Name",
    emailAddress: "Email Address",
    password: "Password",
    signIn: "Login",
    signUp: "Sign Up",
    signOut: "Sign Out",
    alreadyAccount: "Already have an account? Sign In",
    newToApp: "New to HALCYON? Create Account",
    fillAll: "Please fill in all fields",
    enterName: "Please enter your name",
    confirmPassword: "Confirm Password",
    passwordsDontMatch: "Passwords do not match",
    importPhoto: "Choose Photo",
    dashboard: "Dashboard",
    incidents: "Incidents",
    analyze: "Analyze",
    settings: "Settings",
    incidentAgent: "Incident Response Agent",
    online: "Online",
    total: "Total",
    open: "Open",
    resolved: "Resolved",
    rate: "Rate",
    severityDist: "Severity Distribution",
    aiEngineMetrics: "AI Engine Metrics",
    recentIncidents: "Recent Incidents",
    viewAll: "View All",
    newAnalysis: "New Analysis",
    submitLogs: "Submit system logs for AI-powered root cause analysis",
    alertTitle: "Alert Title",
    importLogFile: "Import Log File",
    supportsFiles: "Supports .log, .txt, .json files",
    runAnalysis: "Run HALCYON Analysis",
    about: "About",
    backend: "Backend",
    database: "Database",
    hindsightMemory: "Hindsight Memory",
    systemHealth: "System Health",
    connection: "Connection",
    language: "Language",
    // New Keys
    apiServer: "API Server",
    apiBaseUrl: "API Base URL",
    apiVersion: "API Version",
    dataMode: "Data Mode",
    aiEngine: "AI Engine",
    draftModel: "Draft Model",
    verifierModel: "Verifier Model",
    complianceModel: "Compliance Model",
    cascadeflow: "Cascadeflow",
    sourceCode: "Source Code",
    currentPlan: "Current Plan",
    freePlan: "Free Plan",
    premiumPlan: "Premium Plan ($49)",
    upgradeBtn: "Upgrade to Premium ($49)",
    upgradeTitle: "Upgrade to Premium",
    upgradeDesc: "Unlock unlimited log analysis, advanced verification models, and guaranteed memory cache hits.",
    confirmUpgrade: "Confirm Upgrade",
    cancel: "Cancel",
    successUpgrade: "Successfully upgraded to Premium!",
    account: "Account",
    accountTitle: "Account & Plan",
    accountSubtitle: "Manage your subscription & billing",
    planDetails: "Plan Details",
    currentPlanLabel: "Your Plan",
    features: "Premium Features",
    theme: "Theme",
    darkMode: "Dark",
    lightMode: "Light",
    // GitHub Import
    githubImportTitle: "Import from GitHub",
    githubImportSubtitle: "Fetch log files directly from a GitHub repository",
    githubUrlLabel: "GitHub File URL",
    githubUrlRequired: "Please enter a GitHub URL",
    githubInvalidUrl: "Please enter a valid URL",
    githubNotGithubUrl: "Please enter a GitHub URL (github.com or githubusercontent.com)",
    githubFetchFile: "Fetch Log File",
    githubFetching: "Fetching from GitHub...",
    githubFileReady: "File fetched successfully",
    githubPreview: "Content Preview",
    githubImportBtn: "Import & Analyze",
    githubTryAgain: "Try Again",
    githubErrorTitle: "Failed to Fetch",
    githubFileNotFound: "File not found. Please check the URL and make sure the repository is public.",
    githubRateLimited: "GitHub rate limit reached. Please try again in a few minutes.",
    githubFetchFailed: "Failed to fetch file from GitHub",
    githubEmptyFile: "The file appears to be empty",
    githubFileTooLarge: "File is too large (max 5MB). Please use a smaller log file.",
    githubSupportedFormats: "Supported URL Formats",
    importFromGithub: "GitHub Import",
    githubSignInTitle: "Sign in to GitHub",
    githubSignInDesc: "Provide a Personal Access Token (PAT) to access your private repositories.",
    githubTokenLabel: "Personal Access Token",
    githubTokenPlaceholder: "ghp_xxxxxxxxxxxxxxxxxxxx",
    githubSaveToken: "Save Token",
    githubSignOut: "Sign Out",
  },
  es: {
    welcome: "Bienvenido de nuevo",
    createAccount: "Crear una cuenta",
    fullName: "Nombre completo",
    emailAddress: "Correo electrónico",
    password: "Contraseña",
    signIn: "Iniciar sesión",
    signUp: "Registrarse",
    signOut: "Cerrar sesión",
    alreadyAccount: "¿Ya tienes una cuenta? Iniciar sesión",
    newToApp: "¿Nuevo en HALCYON? Crear una cuenta",
    fillAll: "Por favor complete todos los campos",
    enterName: "Por favor ingrese su nombre",
    confirmPassword: "Confirmar contraseña",
    passwordsDontMatch: "Las contraseñas no coinciden",
    importPhoto: "Elegir foto",
    dashboard: "Panel",
    incidents: "Incidentes",
    analyze: "Analizar",
    settings: "Ajustes",
    incidentAgent: "Agente de Respuesta a Incidentes",
    online: "En línea",
    total: "Total",
    open: "Abiertos",
    resolved: "Resueltos",
    rate: "Tasa",
    severityDist: "Distribución de Severidad",
    aiEngineMetrics: "Métricas del Motor IA",
    recentIncidents: "Incidentes Recientes",
    viewAll: "Ver todo",
    newAnalysis: "Nuevo Análisis",
    submitLogs: "Envíe los registros del sistema para el análisis de causa raíz por IA",
    alertTitle: "Título de la Alerta",
    importLogFile: "Importar archivo de registro",
    supportsFiles: "Soporta archivos .log, .txt, .json",
    runAnalysis: "Ejecutar Análisis HALCYON",
    about: "Acerca de",
    backend: "Servidor",
    database: "Base de Datos",
    hindsightMemory: "Memoria Retrospectiva",
    systemHealth: "Estado del Sistema",
    connection: "Conexión",
    language: "Idioma",
    // New Keys
    apiServer: "Servidor API",
    apiBaseUrl: "URL Base API",
    apiVersion: "Versión de API",
    dataMode: "Modo de Datos",
    aiEngine: "Motor de IA",
    draftModel: "Modelo de Borrador",
    verifierModel: "Modelo Verificador",
    complianceModel: "Modelo de Cumplimiento",
    cascadeflow: "Flujo Cascada",
    sourceCode: "Código Fuente",
    currentPlan: "Plan Actual",
    freePlan: "Plan Gratuito",
    premiumPlan: "Plan Premium ($49)",
    upgradeBtn: "Mejorar a Premium ($49)",
    upgradeTitle: "Mejorar a Premium",
    upgradeDesc: "Desbloquee análisis de registros ilimitados, modelos de verificación avanzados y aciertos de caché de memoria garantizados.",
    confirmUpgrade: "Confirmar Mejora",
    cancel: "Cancelar",
    successUpgrade: "¡Mejorado con éxito a Premium!",
    account: "Cuenta",
    accountTitle: "Cuenta y Plan",
    accountSubtitle: "Administra tu suscripción y facturación",
    planDetails: "Detalles del Plan",
    currentPlanLabel: "Tu Plan",
    features: "Funciones Premium",
    theme: "Tema",
    darkMode: "Oscuro",
    lightMode: "Claro",
    // GitHub Import
    githubImportTitle: "Importar desde GitHub",
    githubImportSubtitle: "Obtener archivos de registro directamente de un repositorio de GitHub",
    githubUrlLabel: "URL del archivo de GitHub",
    githubUrlRequired: "Por favor ingrese una URL de GitHub",
    githubInvalidUrl: "Por favor ingrese una URL válida",
    githubNotGithubUrl: "Por favor ingrese una URL de GitHub (github.com o githubusercontent.com)",
    githubFetchFile: "Obtener archivo de registro",
    githubFetching: "Obteniendo de GitHub...",
    githubFileReady: "Archivo obtenido exitosamente",
    githubPreview: "Vista previa del contenido",
    githubImportBtn: "Importar y analizar",
    githubTryAgain: "Intentar de nuevo",
    githubErrorTitle: "Error al obtener",
    githubFileNotFound: "Archivo no encontrado. Verifique la URL y asegúrese de que el repositorio sea público.",
    githubRateLimited: "Límite de velocidad de GitHub alcanzado. Intente de nuevo en unos minutos.",
    githubFetchFailed: "Error al obtener el archivo de GitHub",
    githubEmptyFile: "El archivo parece estar vacío",
    githubFileTooLarge: "El archivo es demasiado grande (máx 5MB). Use un archivo de registro más pequeño.",
    githubSupportedFormats: "Formatos de URL compatibles",
    importFromGithub: "Importar de GitHub",
    githubSignInTitle: "Iniciar sesión en GitHub",
    githubSignInDesc: "Proporcione un Token de Acceso Personal (PAT) para acceder a sus repositorios privados.",
    githubTokenLabel: "Token de Acceso Personal",
    githubTokenPlaceholder: "ghp_xxxxxxxxxxxxxxxxxxxx",
    githubSaveToken: "Guardar Token",
    githubSignOut: "Cerrar sesión",
  },
  hi: {
    welcome: "वापसी पर स्वागत है",
    createAccount: "खाता बनाएं",
    fullName: "पूरा नाम",
    emailAddress: "ईमेल पता",
    password: "पासवर्ड",
    signIn: "लॉग इन करें",
    signUp: "साइन अप करें",
    signOut: "लॉग आउट करें",
    alreadyAccount: "क्या पहले से एक खाता है? लॉग इन करें",
    newToApp: "HALCYON में नए हैं? खाता बनाएं",
    fillAll: "कृपया सभी फ़ील्ड भरें",
    enterName: "कृपया अपना नाम दर्ज करें",
    confirmPassword: "पासवर्ड की पुष्टि करें",
    passwordsDontMatch: "पासवर्ड मेल नहीं खाते",
    importPhoto: "फ़ोटो चुनें",
    dashboard: "डैशबोर्ड",
    incidents: "घटनाएँ",
    analyze: "विश्लेषण करें",
    settings: "सेटिंग्स",
    incidentAgent: "घटना प्रतिक्रिया एजेंट",
    online: "ऑनलाइन",
    total: "कुल",
    open: "खुले",
    resolved: "सुलझाए गए",
    rate: "दर",
    severityDist: "गंभीरता वितरण",
    aiEngineMetrics: "एआई इंजन मेट्रिक्स",
    recentIncidents: "हालिया घटनाएं",
    viewAll: "सभी देखें",
    newAnalysis: "नया विश्लेषण",
    submitLogs: "एआई-संचालित मूल कारण विश्लेषण के लिए सिस्टम लॉग सबमिट करें",
    alertTitle: "अलर्ट का शीर्षक",
    importLogFile: "लॉग फ़ाइल आयात करें",
    supportsFiles: ".log, .txt, .json फ़ाइलों का समर्थन करता है",
    runAnalysis: "HALCYON विश्लेषण चलाएं",
    about: "के बारे में",
    backend: "बैकएंड",
    database: "डेटाबेस",
    hindsightMemory: "स्मृति",
    systemHealth: "सिस्टम स्वास्थ्य",
    connection: "कनेक्शन",
    language: "भाषा",
    // New Keys
    apiServer: "एपीआई सर्वर",
    apiBaseUrl: "एपीआई बेस यूआरएल",
    apiVersion: "एपीआई संस्करण",
    dataMode: "डेटा मोड",
    aiEngine: "एआई इंजन",
    draftModel: "ड्राफ्ट मॉडल",
    verifierModel: "सत्यापनकर्ता मॉडल",
    complianceModel: "अनुपालन मॉडल",
    cascadeflow: "कैस्केडफ़्लो",
    sourceCode: "स्रोत कोड",
    currentPlan: "वर्तमान योजना",
    freePlan: "नि:शुल्क योजना",
    premiumPlan: "प्रीमियम योजना ($49)",
    upgradeBtn: "प्रीमियम में अपग्रेड करें ($49)",
    upgradeTitle: "प्रीमियम में अपग्रेड करें",
    upgradeDesc: "असीमित लॉग विश्लेषण, उन्नत सत्यापन मॉडल और गारंटीकृत मेमोरी कैश हिट अनलॉक करें।",
    confirmUpgrade: "अपग्रेड की पुष्टि करें",
    cancel: "रद्द करें",
    successUpgrade: "सफलतापूर्वक प्रीमियम में अपग्रेड किया गया!",
    account: "खाता",
    accountTitle: "खाता और योजना",
    accountSubtitle: "अपनी सदस्यता और बिलिंग प्रबंधित करें",
    planDetails: "योजना विवरण",
    currentPlanLabel: "आपकी योजना",
    features: "प्रीमियम सुविधाएं",
    theme: "थीम",
    darkMode: "डार्क",
    lightMode: "लाइट",
    // GitHub Import
    githubImportTitle: "GitHub से आयात करें",
    githubImportSubtitle: "GitHub रिपॉजिटरी से सीधे लॉग फ़ाइलें प्राप्त करें",
    githubUrlLabel: "GitHub फ़ाइल URL",
    githubUrlRequired: "कृपया GitHub URL दर्ज करें",
    githubInvalidUrl: "कृपया एक वैध URL दर्ज करें",
    githubNotGithubUrl: "कृपया GitHub URL दर्ज करें (github.com या githubusercontent.com)",
    githubFetchFile: "लॉग फ़ाइल प्राप्त करें",
    githubFetching: "GitHub से प्राप्त कर रहे हैं...",
    githubFileReady: "फ़ाइल सफलतापूर्वक प्राप्त हुई",
    githubPreview: "सामग्री पूर्वावलोकन",
    githubImportBtn: "आयात करें और विश्लेषण करें",
    githubTryAgain: "फिर से प्रयास करें",
    githubErrorTitle: "प्राप्त करने में विफल",
    githubFileNotFound: "फ़ाइल नहीं मिली। कृपया URL जांचें और सुनिश्चित करें कि रिपॉजिटरी सार्वजनिक है।",
    githubRateLimited: "GitHub दर सीमा पूरी हो गई। कृपया कुछ मिनट बाद पुनः प्रयास करें।",
    githubFetchFailed: "GitHub से फ़ाइल प्राप्त करने में विफल",
    githubEmptyFile: "फ़ाइल खाली प्रतीत होती है",
    githubFileTooLarge: "फ़ाइल बहुत बड़ी है (अधिकतम 5MB)। कृपया छोटी लॉग फ़ाइल का उपयोग करें।",
    githubSupportedFormats: "समर्थित URL प्रारूप",
    importFromGithub: "GitHub से आयात",
    githubSignInTitle: "GitHub में साइन इन करें",
    githubSignInDesc: "अपने निजी रिपॉजिटरी तक पहुंचने के लिए व्यक्तिगत एक्सेस टोकन (PAT) प्रदान करें।",
    githubTokenLabel: "व्यक्तिगत एक्सेस टोकन",
    githubTokenPlaceholder: "ghp_xxxxxxxxxxxxxxxxxxxx",
    githubSaveToken: "टोकन सहेजें",
    githubSignOut: "साइन आउट करें",
  },
  gu: {
    welcome: "ફરી સ્વાગત છે",
    createAccount: "ખાતું બનાવો",
    fullName: "આખું નામ",
    emailAddress: "ઇમેઇલ સરનામું",
    password: "પાસવર્ડ",
    signIn: "સાઇન ઇન",
    signUp: "સાઇન અપ",
    signOut: "સાઇન આઉટ",
    alreadyAccount: "પહેલેથી જ ખાતું છે? સાઇન ઇન કરો",
    newToApp: "HALCYON માં નવા છો? ખાતું બનાવો",
    fillAll: "કૃપા કરીને બધી વિગતો ભરો",
    enterName: "કૃપા કરીને તમારું નામ દાખલ કરો",
    confirmPassword: "પાસવર્ડની પુષ્ટિ કરો",
    passwordsDontMatch: "પાસવર્ડ્સ મેળ ખાતા નથી",
    importPhoto: "ફોટો પસંદ કરો",
    dashboard: "ડેશબોર્ડ",
    incidents: "ઘટનાઓ",
    analyze: "વિશ્લેષણ",
    settings: "સેટિંગ્સ",
    incidentAgent: "ઘટના પ્રતિક્રિયા એજન્ટ",
    online: "ઓનલાઇન",
    total: "કુલ",
    open: "ખુલ્લી",
    resolved: "ઉકેલાયેલ",
    rate: "દર",
    severityDist: "ગંભીરતા વિતરણ",
    aiEngineMetrics: "એઆઈ એન્જિન મેટ્રિક્સ",
    recentIncidents: "તાજેતરની ઘટનાઓ",
    viewAll: "બધા જુઓ",
    newAnalysis: "નવું વિશ્લેષણ",
    submitLogs: "એઆઈ-સંચાલિત વિશ્લેષણ માટે સિસ્ટમ લોગ સબમિટ કરો",
    alertTitle: "એલર્ટ શીર્ષક",
    importLogFile: "લોગ ફાઇલ આયાત કરો",
    supportsFiles: ".log, .txt, .json ફાઇલોને સપોર્ટ કરે છે",
    runAnalysis: "HALCYON વિશ્લેષણ ચલાવો",
    about: "વિશે",
    backend: "બેકએન્ડ",
    database: "ડેટાબેઝ",
    hindsightMemory: "મેમરી",
    systemHealth: "સિસ્ટમ આરોગ્ય",
    connection: "કનેક્શન",
    language: "ભાષા",
    // New Keys
    apiServer: "એપીઆઈ સર્વર",
    apiBaseUrl: "એપીઆઈ બેઝ યુઆરએલ",
    apiVersion: "એપીઆઈ સંસ્કરણ",
    dataMode: "ડેટા મોડ",
    aiEngine: "એઆઈ એન્જિન",
    draftModel: "ડ્રાફ્ટ મોડેલ",
    verifierModel: "ચકાસણીકર્તા મોડેલ",
    complianceModel: "પાલન મોડેલ",
    cascadeflow: "કેસ્કેડફ્લો",
    sourceCode: "સોર્સ કોડ",
    currentPlan: "વર્તમાન યોજના",
    freePlan: "મફત યોજના",
    premiumPlan: "પ્રીમિયમ યોજના ($49)",
    upgradeBtn: "પ્રીમિયમ પર અપગ્રેડ કરો ($49)",
    upgradeTitle: "પ્રીમિયમ પર અપગ્રેડ કરો",
    upgradeDesc: "અમર્યાદિત લોગ વિશ્લેષણ, અદ્યતન ચકાસણી મોડલ્સ અને ગેરંટીડ મેમરી કેશ હિટ્સને અનલૉક કરો.",
    confirmUpgrade: "અપગ્રેડની પુષ્ટિ કરો",
    cancel: "રદ કરો",
    successUpgrade: "સફળતાપૂર્વક પ્રીમિયમ પર અપગ્રેડ કર્યું!",
    account: "ખાતું",
    accountTitle: "ખાતું અને યોજના",
    accountSubtitle: "તમારી સબ્સ્ક્રિપ્શન અને બિલિંગ મેનેજ કરો",
    planDetails: "યોજના વિગતો",
    currentPlanLabel: "તમારી યોજના",
    features: "પ્રીમિયમ સુવિધાઓ",
    theme: "થીમ",
    darkMode: "ડાર્ક",
    lightMode: "લાઇટ",
    // GitHub Import
    githubImportTitle: "GitHub થી આયાત કરો",
    githubImportSubtitle: "GitHub રિપોઝીટરીમાંથી સીધી લોગ ફાઇલો મેળવો",
    githubUrlLabel: "GitHub ફાઇલ URL",
    githubUrlRequired: "કૃપા કરીને GitHub URL દાખલ કરો",
    githubInvalidUrl: "કૃપા કરીને એક માન્ય URL દાખલ કરો",
    githubNotGithubUrl: "કૃપા કરીને GitHub URL દાખલ કરો (github.com અથવા githubusercontent.com)",
    githubFetchFile: "લોગ ફાઇલ મેળવો",
    githubFetching: "GitHub થી મેળવી રહ્યા છીએ...",
    githubFileReady: "ફાઇલ સફળતાપૂર્વક મેળવી",
    githubPreview: "સામગ્રી પૂર્વાવલોકન",
    githubImportBtn: "આયાત કરો અને વિશ્લેષણ કરો",
    githubTryAgain: "ફરી પ્રયાસ કરો",
    githubErrorTitle: "મેળવવામાં નિષ્ફળ",
    githubFileNotFound: "ફાઇલ મળી નથી. કૃપા કરીને URL તપાસો અને ખાતરી કરો કે રિપોઝીટરી જાહેર છે.",
    githubRateLimited: "GitHub રેટ લિમિટ પહોંચી ગઈ. કૃપા કરીને થોડી મિનિટો પછી ફરીથી પ્રયાસ કરો.",
    githubFetchFailed: "GitHub થી ફાઇલ મેળવવામાં નિષ્ફળ",
    githubEmptyFile: "ફાઇલ ખાલી હોવાનું લાગે છે",
    githubFileTooLarge: "ફાઇલ ખૂબ મોટી છે (મહત્તમ 5MB). કૃપા કરીને નાની લોગ ફાઇલનો ઉપયોગ કરો.",
    githubSupportedFormats: "સમર્થિત URL ફોર્મેટ",
    importFromGithub: "GitHub થી આયાત",
    githubSignInTitle: "GitHub માં સાઇન ઇન કરો",
    githubSignInDesc: "તમારા ખાનગી રિપોઝીટરીઝને ઍક્સેસ કરવા માટે વ્યક્તિગત ઍક્સેસ ટોકન (PAT) પ્રદાન કરો.",
    githubTokenLabel: "વ્યક્તિગત ઍક્સેસ ટોકન",
    githubTokenPlaceholder: "ghp_xxxxxxxxxxxxxxxxxxxx",
    githubSaveToken: "ટોકન સાચવો",
    githubSignOut: "સાઇન આઉટ કરો",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  hasSelectedLanguage: boolean;
  setHasSelectedLanguage: (val: boolean) => void;
  t: (key: keyof typeof translations.en) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");
  const [hasSelectedLanguage, setHasSelectedLanguage] = useState<boolean>(false);

  const t = (key: keyof typeof translations.en) => {
    return translations[language][key] || translations.en[key] || String(key);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, hasSelectedLanguage, setHasSelectedLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useTranslation() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useTranslation must be used within a LanguageProvider");
  }
  return context;
}
