import { Incident, MemoryFix, AuditLog, MetricSummary } from '@/types/incident';

export const MOCK_METRICS: MetricSummary = {
  activeIncidents: 3,
  aiConfidenceScore: 98.4,
  averageLatencyMs: 42,
  systemUptimePercentage: 99.98,
  memoryMatchRate: 94.2,
  totalCostSavedUSD: 148500,
};

export const MOCK_INCIDENTS: Incident[] = [
  {
    id: 'INC-8924',
    title: 'Kubernetes Pod Out Of Memory (OOMKilled) in Payment Gateway API',
    service: 'payment-gateway-api',
    severity: 'CRITICAL',
    status: 'ACTIVE',
    timestamp: '2026-07-31T13:12:00Z',
    durationMinutes: 14,
    mttrMinutes: 8,
    memoryMatchPercentage: 98,
    costSavedUSD: 18500,
    rootCause: 'Heap exhaustion due to unindexed DB scan in webhook listener thread pool.',
    summary: 'High memory consumption caused pod restart loops during peak traffic surge. AI memory engine detected identical pattern from INC-4412.',
    aiSuggestedFix: 'kubectl scale deployment payment-gateway --replicas=8 && update JVM max ram limit to 4Gi.',
    affectedNodesCount: 12,
    logs: [
      '[13:12:01.442] ERROR [payment-gateway] java.lang.OutOfMemoryError: Java heap space',
      '[13:12:02.109] WARN  [k8s-kubelet] Container payment-api-pod-3 failed OOMKilled check (exit code 137)',
      '[13:12:04.881] INFO  [halcyon-ai] Pattern match detected: INC-4412 (98% similarity index)',
      '[13:12:05.120] ACTION [halcyon-agent] Proposed automated fix vector scaling to replicas=8',
    ],
    matchedFixId: 'FIX-104',
    tags: ['kubernetes', 'oom', 'payment-api', 'jvm'],
  },
  {
    id: 'INC-8923',
    title: 'PostgreSQL Primary Connection Pool Starvation',
    service: 'db-cluster-primary',
    severity: 'HIGH',
    status: 'INVESTIGATING',
    timestamp: '2026-07-31T12:45:00Z',
    durationMinutes: 41,
    mttrMinutes: 15,
    memoryMatchPercentage: 91,
    costSavedUSD: 12000,
    rootCause: 'Long-running analytics queries acquiring write locks on user_profiles table.',
    summary: 'Max connection limit (500) reached. Client queries hanging in idle-in-transaction state.',
    aiSuggestedFix: 'SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE state = \'idle in transaction\' AND age(clock_timestamp(), query_start) > interval \'5 minutes\';',
    affectedNodesCount: 4,
    logs: [
      '[12:45:10.004] FATAL [postgres] remaining connection slots are reserved for non-replication superuser connections',
      '[12:45:14.221] WARN  [pgbouncer] client login timeout: pool user_db exhausted',
      '[12:46:01.002] INFO  [halcyon-ai] Memory match retrieved: INC-6721 (91% confidence)',
    ],
    matchedFixId: 'FIX-209',
    tags: ['postgres', 'pgbouncer', 'database', 'connection-pool'],
  },
  {
    id: 'INC-8922',
    title: 'Redis Cluster Split-Brain Event & Key Eviction Surge',
    service: 'cache-redis-prod',
    severity: 'MEDIUM',
    status: 'RESOLVED',
    timestamp: '2026-07-31T11:20:00Z',
    durationMinutes: 19,
    mttrMinutes: 6,
    memoryMatchPercentage: 96,
    costSavedUSD: 9400,
    rootCause: 'Network partition between AWS us-east-1a and us-east-1b availability zones.',
    summary: 'Sentinel failover triggered concurrently on node-2 and node-4.',
    aiSuggestedFix: 'redis-cli -h redis-master-1 SENTINEL FAILOVER mymaster',
    affectedNodesCount: 6,
    logs: [
      '[11:20:00.119] WARN  [redis-sentinel] +sdown master mymaster 10.0.4.12',
      '[11:20:05.441] INFO  [halcyon-ai] Automated sentinel re-sync initiated.',
    ],
    matchedFixId: 'FIX-301',
    tags: ['redis', 'sentinel', 'cache', 'aws'],
  },
];

export const MOCK_MEMORY_FIXES: MemoryFix[] = [
  {
    id: 'FIX-104',
    title: 'JVM Heap Exhaustion & Pod Replicas Auto-Scaler Fix',
    service: 'payment-gateway-api',
    resolutionTimeMs: 180000,
    confidenceScore: 98.4,
    fixCommand: 'kubectl set resources deployment/payment-gateway -c=app --limits=memory=4Gi,cpu=2000m',
    explanation: 'Scales memory limits to prevent OOMKilled signals while flushing unindexed query buffers.',
    author: 'Halcyon AI Engine',
    createdAt: '2026-06-15T09:12:00Z',
    tags: ['kubernetes', 'jvm', 'oom', 'autoscaling'],
    timesApplied: 42,
  },
  {
    id: 'FIX-209',
    title: 'PostgreSQL Idle-in-Transaction Connection Terminator',
    service: 'db-cluster-primary',
    resolutionTimeMs: 45000,
    confidenceScore: 94.2,
    fixCommand: 'ALTER SYSTEM SET idle_in_transaction_session_timeout = \'30000\'; SELECT pg_reload_conf();',
    explanation: 'Automatically terminates stale client backend connections holding locks longer than 30s.',
    author: 'Sarah Jenkins (Lead SRE)',
    createdAt: '2026-07-02T14:30:00Z',
    tags: ['postgres', 'connection-pool', 'lock-contention'],
    timesApplied: 89,
  },
];

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'AUD-9912',
    action: 'AI_AUTOMATED_MITIGATION',
    actor: 'Halcyon Auto-Fix Bot',
    timestamp: '2026-07-31T13:14:02Z',
    target: 'payment-gateway-api Deployment',
    ipAddress: '10.240.0.12',
    status: 'SUCCESS',
    details: 'Applied FIX-104 vector: Scaled replicas from 4 to 8 and increased memory allocation.',
  },
  {
    id: 'AUD-9911',
    action: 'USER_LOGIN_SUCCESS',
    actor: 'maharshi.patel@halcyon.ai',
    timestamp: '2026-07-31T13:02:11Z',
    target: 'Web Operator Console',
    ipAddress: '192.168.1.104',
    status: 'SUCCESS',
    details: 'Authenticated via Firebase Google OAuth (MFA verified).',
  },
];
